# .github/workflows/publish.yml

name: Publish to PyPI

# This workflow runs when a new tag is pushed that starts with 'v'
# e.g., v0.1.0, v1.2.3
on:
  push:
    tags:
      - 'v*'

jobs:
  publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    
    # These permissions are necessary to authenticate with PyPI using OpenID Connect.
    # It's a more secure method than using a long-lived API token.
    permissions:
      id-token: write # This is required for trusted publishing
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.x"

      - name: Install build dependencies
        run: python -m pip install build

      - name: Build package
        run: python -m build

      - name: Publish package to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

